org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedOptionWarnings=true
kotlin.stdlib.default.dependency=false

android.newDsl=false
android.builtInKotlin=false
