name: RodsDepengloper
description: "Bug WhatsApp Crasher"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.0.0

  # Network & API
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  connectivity_plus: ^6.0.3
  network_info_plus: ^4.1.0
  xml: ^6.5.0

  # Device Info & Sensors
  device_info_plus: ^10.1.0
  battery_plus: ^6.0.3
  geolocator: ^12.0.0
  permission_handler: ^11.0.0
  vibration: any

  # Storage & Local Data
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.2

  # Media (Audio & Video)
  video_player: ^2.9.2
  chewie: ^1.5.2
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audioplayers: ^5.2.1
  image_picker: ^1.0.7
  flutter_sound: ^9.2.13

  # Utils & Others
  url_launcher: ^6.2.6
  share_plus: ^7.0.1
  intl: ^0.19.0
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/icon/icon.jpg
  image_path_ios: assets/icon/icon/icon.jpg
  image_path: assets/icon/icon.jpg
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/logo.png
    - assets/images/reze.png
    - assets/videos/landing.mp4
    - assets/videos/splash.mp4
    - assets/videos/banner.mp4
    - assets/videos/background.mp4
    - assets/images/banner.jpg
    - assets/images/pp.jpg
    - assets/images/sidebar.jpg
    - assets/images/background.jpg
    - assets/sound/background.mp3

  fonts:
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Regular.ttf
    - family: ShareTechMono
      fonts:
        - asset: fonts/ShareTechMono-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
        - asset: fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: fonts/Orbitron-Bold.ttf
          weight: 700
        - asset: fonts/Orbitron-SemiBold.ttf
          weight: 600
        - asset: fonts/Orbitron-ExtraBold.ttf
          weight: 800
        - asset: fonts/Orbitron-Black.ttf
          weight: 900
